### ISSUE TITLE
Préparer les requètes pour chaque critère

### ISSUE THREAD

**Issue by WTFlay** [ImOff/prestashop#5]

**Comment by foyjoo** [comment]
/////***** Newsletter *****/////
        $sql = new DbQuery();
        $sql->select('*');
        $sql->from('customer');
        $sql->where('newsletter = @');
        return Db::getInstance()->executeS($sql);


        /////***** Optin *****/////
        $sql = new DbQuery();
        $sql->select('*');
        $sql->from('customer');
        $sql->where('optin = @');
        return Db::getInstance()->executeS($sql);


        /////***** Customer group *****/////
        $sql = new DbQuery();
        $sql->select('*');
        $sql->from('customer');
        $sql->where('id_group = @');
        return Db::getInstance()->executeS($sql);

        /////***** Language *****/////
        $sql = new DbQuery();
        $sql->select('*');
        $sql->from('customer');
        $sql->where('id_lang = @');
        return Db::getInstance()->executeS($sql);

        /////***** Age *****/////
        $sql = new DbQuery();
        $sql->select DATEDIFF('*');
        $sql->from('customer');
        $sql->where('birthday');
        $sql->between('@','@')
        return Db::getInstance()->executeS($sql);
